### ISSUE TITLE
[Feature] Flink Tutorial scala code

### ISSUE THREAD

**Issue by gaotingkai** [SophiaData/Bigdata_Code_Tutorial#125]
### Search before asking

- [X] I had searched in the [issues](https://github.com/SophiaData/Bigdata_Code_Tutorial/issues) and found no similar feature requirement.

### Description

Provide scala code example

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rookiegao** [comment]
active
